name: Deploy

on:
  pull_request:
    types:
      - closed
    labels:
      - CI:Deploy
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Set up Docker Compose
      uses: hoverkraft-tech/compose-action@v2.1.0
      with:
        compose-file: './docker-compose.yaml'

    - name: Wait for 10 seconds
      run: sleep 10

    - name: Check chaindata folder
      run: |
        ls -lah ./go-ethereum/data/geth/chaindata
    
    - name: Install hardhat
      run: |
        cd hardhat
        npm install --save-dev hardhat

    - name: Deploy contracts
      run: |
        cd hardhat
        npx hardhat run scripts/deploy.js --network localhost

    - name: Check chaindata
      run: |
        ls -lah ./go-ethereum/data/geth/chaindata

    - name: Run Hardhat tests
      run: |
        cd hardhat
        npx hardhat test

    - name: Change directory ownership
      run: sudo chown -R $USER:$USER ./go-ethereum/data

    - name: Set file permissions
      run: chmod -R 755 ./go-ethereum/data

    - name: Build Docker image with deployed contracts
      run: |
        docker build -t ssymbiotik7/hat:latest .

    - name: Push Docker image to registry
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push ssymbiotik7/hat:latest
